### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by qn06142** [behrad2k/tungeos#1]
system: windows 11 with probably messed up dev tools

command: make iso

output:
```
process_begin: CreateProcess(NULL, which i686-elf-gcc, ...) failed.
Makefile:11: pipe: No error
Makefile:12: *** "get i686-elf-gcc".  Stop.
```
expected:
iso file somewhere

**Comment by therealtunge** [comment]
install i686-elf-gcc lol

**Comment by qn06142** [comment]
what even is that

**Comment by therealtunge** [comment]
cross compiler for c

**Comment by qn06142** [comment]
how do i install that on windows

**Comment by therealtunge** [comment]
use wsl

**Comment by qn06142** [comment]
nvm im going to make myself suffer

**Comment by qn06142** [comment]
thanks for helping

**Comment by therealtunge** [comment]
uhhh why arent you using wsl
